### ISSUE TITLE
Cannot start invoker

### ISSUE THREAD

**Issue by gazben** [xingzhou/Deploy_OpenWhisk_with_Helm#16]
Using the latest version of the chart. Log:

```

[2018-03-26T11:54:36.817Z] [INFO] Initializing Kamon...
[INFO] [03/26/2018 11:54:39.294] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[2018-03-26T11:54:39.893Z] [INFO] Slf4jLogger started
[2018-03-26T11:54:42.832Z] [INFO] [??] [Config] environment set value for limits.actions.sequence.maxLength
[2018-03-26T11:54:42.965Z] [INFO] [??] [Config] environment set value for limits.triggers.fires.perMinute
[2018-03-26T11:54:42.966Z] [INFO] [??] [Config] environment set value for akka.cluster.seed.nodes
[2018-03-26T11:54:43.124Z] [INFO] [??] [Config] environment set value for controller.instances
[2018-03-26T11:54:43.125Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent
[2018-03-26T11:54:43.151Z] [INFO] [??] [Config] environment set value for controller.localBookkeeping
[2018-03-26T11:54:43.152Z] [INFO] [??] [Config] environment set value for whisk.version.date
[2018-03-26T11:54:43.153Z] [INFO] [??] [Config] environment set value for whisk.version.buildno
[2018-03-26T11:54:43.154Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute
[2018-03-26T11:54:43.154Z] [INFO] [??] [Config] environment set value for kafka.hosts
[2018-03-26T11:54:43.159Z] [INFO] [??] [Config] environment set value for runtimes.manifest
[2018-03-26T11:54:43.160Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem
[2018-03-26T11:54:43.161Z] [INFO] [??] [Config] environment set value for port
[2018-03-26T11:54:46.877Z] [INFO] [??] [KafkaMessagingProvider] topic completed1 already existed
[2018-03-26T11:54:51.209Z] [INFO] [??] [KafkaMessagingProvider] topic health already existed
[2018-03-26T11:54:54.936Z] [INFO] [??] [KafkaMessagingProvider] topic cacheInvalidation already existed
[2018-03-26T11:54:56.306Z] [INFO] [#sid_130] [Controller] starting controller instance 1 [marker:controller_startup1_count:13669]
Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a whisk.core.database.CouchDbConfig. Failures are:
  at 'whisk':
    - Key not found: 'couchdb'.
	at pureconfig.package$.getResultOrThrow(package.scala:138)
	at pureconfig.package$.loadConfigOrThrow(package.scala:160)
	at whisk.core.database.CouchDbStoreProvider$.makeStore(CouchDbStoreProvider.scala:56)
	at whisk.core.entity.WhiskAuthStore$.datastore(WhiskStore.scala:90)
	at whisk.core.controller.Controller.&lt;init&gt;(Controller.scala:108)
	at whisk.core.controller.Controller$.main(Controller.scala:232)
	at whisk.core.controller.Controller.main(Controller.scala)
[INFO] [03/26/2018 11:54:59.294] [kamon-shutdown-hook-1] [CoordinatedShutdown(akka://kamon)] Starting coordinated shutdown from JVM shutdown hook
[2018-03-26T11:54:59.310Z] [INFO] Starting coordinated shutdown from JVM shutdown hook
[2018-03-26T11:54:59.354Z] [INFO] [??] [Controller] Shutting down Kamon with coordinated shutdown

```

**Comment by gazben** [comment]
@xingzhou Can you help me on this?

**Comment by xingzhou** [comment]
@gazben, are you using the latest container images?

**Comment by gazben** [comment]
@xingzhou I pulled the master branch, created the namespace, disabled the node affinity and set the NodePorts, to match the other services in the cluster. 
Should I set  anything else?

**Comment by gazben** [comment]
@xingzhou And another important thing, I am using minikube v0.25.0

**Comment by xingzhou** [comment]
ok, let me take a look at the latest images first

**Comment by xingzhou** [comment]
@gazben, please check the latest code, should have fixed the issue. Note that at present, controller needs to wait for couch db to start. But couch db may take some time to launch, so during this time, controller may restart for several times and I'm going to improve this in the future.

Please change all the `imagePullPolicy` to `Always` in the `values.yml` so that you can try the deployment based on latest images.

**Comment by gazben** [comment]
@xingzhou Thank you, all the pods are up and running.
