### ISSUE TITLE
Cannot convert configuration to a whisk.core.controller.WhiskInformation.  Key not found: 'info'

### ISSUE THREAD

**Issue by gazben** [xingzhou/Deploy_OpenWhisk_with_Helm#17]
Hello

Updated to the latest version and, on startup the controller fails with the message below:

```
 Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a whisk.core.controller.WhiskInformation. Failures are:
  at 'whisk':
    - Key not found: 'info'.
	at pureconfig.package$.getResultOrThrow(package.scala:138)
	at pureconfig.package$.loadConfigOrThrow(package.scala:160)
	at whisk.core.controller.RestAPIVersion.&lt;init&gt;(RestAPIs.scala:176)
	at whisk.core.controller.Controller.&lt;init&gt;(Controller.scala:133)
	at whisk.core.controller.Controller$.main(Controller.scala:241)
	at whisk.core.controller.Controller.main(Controller.scala) 
```

Did I miss something?

**Comment by gazben** [comment]
@xingzhou Can you help me?

**Comment by joluc** [comment]
Same issue here! @gazben did you solve it eventually?

**Comment by joluc** [comment]
I guess that explains it: https://github.com/apache/incubator-openwhisk-deploy-kube/issues/235#issuecomment-403913461

**Comment by gazben** [comment]
@jonathanschwarze I got to the same conclusion that somehow the config is not compatible with the current version. Our "solution" was a dedicated Openwhisk server running on ubuntu 14.04.
